### ISSUE TITLE
New line issue in the "json" helper

### ISSUE THREAD

**Issue by marc0l92** [nknapp/bootprint-base#15]
# Issue description
The 'json' helper function adds an extra new line at the end of the parsed object. This happens because the parsed result is inside the `<pre>` HTML tag.
## Example
```
{
    "title": "This is an example object",
    "message": "The 'json' helper will add an additional new line after the object"
}
                     
```

# Proposed solution
Remove the new line from the parsed 'json' objects:
in the file `/handlebars/helpers.js` modify the line 171 in order to make it like:
```
return new Handlebars.SafeString($.html().replace(/\n/g, ''))
```

_If you want I can submit a Pull Request._

**Comment by nknapp** [comment]
Feel free. But removing "all" newlines seems too much to me. Wouldn't it be enough to remove the last one?

**Comment by marc0l92** [comment]
I decided to remove all the new line in order to make the code work also when you decide to upgrade the library that prettify the json object to HTML.
